"use client";

import { CalendarDays, LoaderCircle, Plus, RefreshCw, UserRoundPlus, XCircle } from "lucide-react";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";

type Item = { id: string; serviceType: "BREAKFAST" | "LUNCH"; name: string; price: string };
type Day = { id: string; serviceDate: string; items: Item[] };
type RecordItem = { id: string; guestName: string; guestType: "PROVIDER" | "VISITOR" | "NEW_HIRE" | "OTHER"; company: string | null; quantity: number; priceApplied: string; chargeType: "YELLOWFLEX" | "PROVIDER" | "COURTESY" | "OTHER"; areaResponsible: string | null; reason: string; notes: string | null; status: "ACTIVE" | "CANCELLED"; createdAt: string; authorizedBy: { name: string; email:string }; menuItem: { id: string; serviceType: "BREAKFAST" | "LUNCH"; name: string; price: string; menuDay: { serviceDate: string } } };
type Data = { week: { id: string; weekStart: string; days: Day[] } | null; records: RecordItem[] };

const dateFormatter = new Intl.DateTimeFormat("es-MX", { weekday: "short", day: "numeric", month: "short", timeZone: "UTC" });
const money = new Intl.NumberFormat("es-MX", { style: "currency", currency: "MXN" });
const guestLabels = { PROVIDER: "Proveedor", VISITOR: "Visitante", NEW_HIRE: "Nuevo ingreso", OTHER: "Otro" } as const;
const chargeLabels = { YELLOWFLEX: "YellowFlex", PROVIDER: "Proveedor", COURTESY: "Cortesía", OTHER: "Otro" } as const;

export default function HrExtraordinaryDashboard() {
  const [data, setData] = useState<Data>(); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState<string>();
  const load = useCallback(async () => { try { setLoading(true); setError(undefined); const response = await fetch("/api/food-services/hr/extraordinary", { cache: "no-store" }); const payload = await response.json() as { data?: Data; error?: string }; if (!response.ok) throw new Error(payload.error ?? "No fue posible consultar los consumos extraordinarios."); setData(payload.data); } catch(e) { setError(e instanceof Error ? e.message : "No fue posible consultar los consumos extraordinarios."); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const active = useMemo(() => data?.records.filter((record) => record.status === "ACTIVE") ?? [], [data]);
  const totalServices = active.reduce((sum, record) => sum + record.quantity, 0);

  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const formElement = event.currentTarget; const form = new FormData(formElement); try { setSaving(true); setError(undefined); const response = await fetch("/api/food-services/hr/extraordinary", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ menuItemId: form.get("menuItemId"), guestName: form.get("guestName"), guestType: form.get("guestType"), company: form.get("company"), quantity: Number(form.get("quantity")), chargeType: form.get("chargeType"), areaResponsible: form.get("areaResponsible"), reason: form.get("reason"), notes: form.get("notes") }) }); const payload = await response.json() as { error?: string }; if (!response.ok) throw new Error(payload.error ?? "No fue posible registrar el servicio."); formElement.reset(); await load(); } catch (e) { setError(e instanceof Error ? e.message : "No fue posible registrar el servicio."); } finally { setSaving(false); } }
  async function cancel(id: string) { if (!window.confirm("¿Cancelar este consumo extraordinario? El registro conservará su trazabilidad.")) return; try { const response = await fetch("/api/food-services/hr/extraordinary", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ id }) }); const payload = await response.json() as { error?: string }; if (!response.ok) throw new Error(payload.error ?? "No fue posible cancelar el registro."); await load(); } catch (e) { setError(e instanceof Error ? e.message : "No fue posible cancelar el registro."); } }

  return <section className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm">
    <div className="flex flex-col gap-4 border-b border-slate-200 bg-slate-50 px-6 py-6 lg:flex-row lg:items-center lg:justify-between"><div><div className="flex items-center gap-2 text-[#0B3A82]"><UserRoundPlus className="size-5"/><p className="text-xs font-black uppercase tracking-[.18em]">Consumos extraordinarios</p></div><h2 className="mt-2 text-2xl font-black text-slate-950">Invitados, proveedores y nuevos ingresos</h2><p className="mt-2 text-sm text-slate-500">Registra servicios fuera del flujo normal de colaboradores sin contaminar la plantilla de RH.</p></div><div className="flex items-center gap-3"><span className="rounded-xl border border-amber-200 bg-amber-50 px-4 py-2 text-sm font-black text-[#8a6200]">{totalServices} servicio(s) activos</span><button onClick={()=> void load()} disabled={loading} className="flex size-10 items-center justify-center rounded-xl border border-slate-200 bg-white text-[#0B3A82]"><RefreshCw className={`size-4 ${loading ? "animate-spin" : ""}`}/></button></div></div>
    <div className="grid gap-6 p-6 xl:grid-cols-[.9fr_1.1fr]">
      <form onSubmit={submit} className="space-y-4 rounded-2xl border border-slate-200 p-5"><div className="flex items-center gap-2"><Plus className="size-4 text-[#F4B400]"/><h3 className="font-black text-slate-900">Nuevo servicio extraordinario</h3></div>
        {!data?.week ? <p className="rounded-xl bg-amber-50 p-4 text-sm font-semibold text-amber-800">No existe una semana publicada. Publica el menú antes de registrar invitados.</p> : <>
        <label className="block text-sm font-bold text-slate-700">Platillo<select name="menuItemId" required className="mt-2 h-11 w-full rounded-xl border border-slate-200 bg-white px-3 font-medium"> <option value="">Seleccionar...</option>{data.week.days.flatMap(day => day.items.map(item => <option key={item.id} value={item.id}>{dateFormatter.format(new Date(day.serviceDate))} · {item.serviceType === "BREAKFAST" ? "Desayuno" : "Comida"} · {item.name}</option>))}</select></label>
        <div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-bold text-slate-700">Nombre / referencia<input name="guestName" required maxLength={120} className="mt-2 h-11 w-full rounded-xl border border-slate-200 px-3"/></label><label className="text-sm font-bold text-slate-700">Tipo<select name="guestType" required className="mt-2 h-11 w-full rounded-xl border border-slate-200 px-3"><option value="PROVIDER">Proveedor</option><option value="VISITOR">Visitante</option><option value="NEW_HIRE">Nuevo ingreso</option><option value="OTHER">Otro</option></select></label></div>
        <div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-bold text-slate-700">Empresa / origen<input name="company" maxLength={120} className="mt-2 h-11 w-full rounded-xl border border-slate-200 px-3"/></label><label className="text-sm font-bold text-slate-700">Cantidad<input name="quantity" type="number" min="1" max="50" defaultValue="1" required className="mt-2 h-11 w-full rounded-xl border border-slate-200 px-3"/></label></div>
        <div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-bold text-slate-700">Responsable del costo<select name="chargeType" required className="mt-2 h-11 w-full rounded-xl border border-slate-200 px-3"><option value="YELLOWFLEX">YellowFlex</option><option value="PROVIDER">Proveedor</option><option value="COURTESY">Cortesía</option><option value="OTHER">Otro</option></select></label><label className="text-sm font-bold text-slate-700">Área responsable<input name="areaResponsible" maxLength={120} placeholder="RH, Dirección..." className="mt-2 h-11 w-full rounded-xl border border-slate-200 px-3"/></label></div>
        <label className="block text-sm font-bold text-slate-700">Motivo<input name="reason" required maxLength={240} className="mt-2 h-11 w-full rounded-xl border border-slate-200 px-3"/></label><label className="block text-sm font-bold text-slate-700">Observaciones<textarea name="notes" maxLength={500} rows={3} className="mt-2 w-full rounded-xl border border-slate-200 p-3"/></label>
        <button disabled={saving} className="inline-flex h-11 w-full items-center justify-center gap-2 rounded-xl bg-[#0B3A82] px-4 text-sm font-black text-white">{saving && <LoaderCircle className="size-4 animate-spin"/>}Registrar y enviar a cocina</button></>}
      </form>
      <div><h3 className="font-black text-slate-900">Trazabilidad de la semana</h3>{error && <p className="mt-3 rounded-xl border border-red-200 bg-red-50 p-3 text-sm font-semibold text-red-700">{error}</p>}{loading && !data ? <p className="mt-6 text-sm text-slate-500">Consultando...</p> : active.length === 0 ? <p className="mt-4 rounded-2xl border border-dashed border-slate-300 bg-slate-50 p-8 text-center text-sm font-semibold text-slate-500">No hay consumos extraordinarios activos.</p> : <div className="mt-4 space-y-3">{active.map(record => <article key={record.id} className="rounded-2xl border border-slate-200 p-4"><div className="flex items-start justify-between gap-4"><div><div className="flex flex-wrap items-center gap-2"><span className="rounded-lg bg-blue-50 px-2 py-1 text-xs font-black text-[#0B3A82]">{guestLabels[record.guestType]}</span><span className="text-xs font-bold text-slate-400">{dateFormatter.format(new Date(record.menuItem.menuDay.serviceDate))}</span></div><p className="mt-2 font-black text-slate-900">{record.guestName}</p><p className="mt-1 text-sm text-slate-600">{record.quantity} × {record.menuItem.name} · {money.format(Number(record.priceApplied) * record.quantity)}</p><p className="mt-1 text-xs text-slate-500">Cargo: {chargeLabels[record.chargeType]} · Motivo: {record.reason}</p><p className="mt-1 text-xs text-slate-400">Autorizó: {record.authorizedBy.name}</p></div><button type="button" onClick={() => void cancel(record.id)} className="rounded-lg p-2 text-slate-400 hover:bg-red-50 hover:text-red-600" title="Cancelar"><XCircle className="size-4"/></button></div></article>)}</div>}</div>
    </div>
  </section>;
}
