import { ArrowRight, ChefHat, ClipboardCheck, UsersRound, Utensils } from "lucide-react";
import Link from "next/link";
import PageHeader from "@/components/page-header";

const areas = [
  { title: "Portal del empleado", description: "Identificación por número y PIN para consultar el menú publicado y reservar.", href: "/modules/food-services/employee", icon: Utensils },
  { title: "Gestión de menú", description: "Área para chef: borradores, opciones, publicación e historial semanal.", href: "/modules/food-services/chef", icon: ChefHat },
  { title: "Registro de consumo", description: "Operación separada de la reserva, lista para credenciales futuras.", href: "/modules/food-services/consumption", icon: ClipboardCheck },
  { title: "Administración RH", description: "Empleados, reservas, consumos, filtros y preparación para cobros.", href: "/modules/food-services/hr", icon: UsersRound },
];
export default function FoodServicesPage() { return <div className="space-y-8"><PageHeader eyebrow="Módulo corporativo" title="Food Services" description="Comedor industrial con trazabilidad desde el menú publicado hasta el consumo efectivo." /><section className="rounded-2xl border border-slate-200 bg-white p-6 sm:p-8"><div className="flex flex-col justify-between gap-4 sm:flex-row"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#b27f00]">Estado operativo</p><h2 className="mt-2 text-2xl font-bold text-slate-900">Información en tiempo real</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">Los indicadores aparecerán cuando exista información publicada en PostgreSQL. No se muestran métricas ficticias.</p></div><span className="h-fit rounded-full bg-slate-100 px-3 py-1.5 text-xs font-semibold text-slate-500">Sin datos disponibles</span></div><div className="mt-7 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{["Menú semanal", "Reservas", "Consumos", "Importe acumulado"].map((label) => <div key={label} className="rounded-xl border border-slate-100 bg-slate-50 p-4"><p className="text-xs font-medium text-slate-500">{label}</p><p className="mt-2 text-sm font-semibold text-slate-400">Pendiente de datos</p></div>)}</div></section><section className="grid gap-4 md:grid-cols-2">{areas.map(({ title, description, href, icon: Icon }) => <Link key={href} href={href} className="group rounded-2xl border border-slate-200 bg-white p-6 shadow-sm transition hover:-translate-y-0.5 hover:border-blue-200 hover:shadow-lg hover:shadow-blue-950/5"><span className="flex size-11 items-center justify-center rounded-xl bg-blue-50 text-[#0b3a82]"><Icon className="size-5" /></span><h2 className="mt-5 text-lg font-bold text-slate-900">{title}</h2><p className="mt-2 text-sm leading-6 text-slate-500">{description}</p><span className="mt-5 flex items-center gap-2 text-sm font-bold text-[#0b3a82]">Abrir área <ArrowRight className="size-4 transition-transform group-hover:translate-x-1" /></span></Link>)}</section></div>; }
